version: "3.8"

services:
  account_management:
    image: mydockerhubuser/account_management:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/banking

  transaction-service:
    image: mydockerhubuser/transaction-service:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/bankings

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
